"""
Django settings for drf_tutotial_brucepang project.

Generated by 'django-admin startproject' using Django 4.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m$^98uk5qw^2zqrh+t*9^fx8r*b0y&9!(@9qbjeb6#y8ze@4!0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework.authtoken', # DRF的token认证
    'rest_framework',
    'course.apps.CourseConfig', # 注册course应用
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'drf_tutotial_brucepang.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': []
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'drf_tutotial_brucepang.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # 'NAME': os.path.join(BASE_DIR, "db.sqlite3"), # 兼容老版本的写法
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# STATIC_ROOT = os.path.join(BASE_DIR, "static") # DRF有前端文件，使用connect-staticfiles处理静态文件会全部放到此目录
STATIC_ROOT = BASE_DIR / 'static' # DRF有前端文件，使用connect-staticfiles处理静态文件会全部放到此目录

STATICFILES_DIRS = [
    # os.path.join(BASE_DIR, "staticfiles"),
    BASE_DIR / 'staticfiles',
]
# DRF全局配置
REST_FRAMEWORK = {
    # "DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.coreapi.AutoSchema",
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    'DEFAULT_RENDERER_CLASSES': [ # DRF返回Response时默认使用的渲染器
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer', # DRF默认的渲染器
    ],
    'DEFAULT_PARSER_CLASSES': [ # 解析request.data
        'rest_framework.parsers.JSONParser', # 解析请求体的JSON数据
        'rest_framework.parsers.FormParser', # 解析请求体的表单数据
        'rest_framework.parsers.MultiPartParser', # 解析请求体的文件数据
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [ # DRF默认的认证类
        'rest_framework.authentication.BasicAuthentication', # 用户名密码认证（基于Base64在请求头传递，可以轻易解密）
        'rest_framework.authentication.SessionAuthentication', # session认证, 需要开启CSRF token， 否则会报403错误
        'rest_framework.authentication.TokenAuthentication', # token认证
    ],
    # 'DEFAULT_PERMISSION_CLASSES': [ # DRF默认的权限类（全局设置）
    #     # 'rest_framework.permissions.AllowAny', # 任何用户都可以访问（默认）
    #     'rest_framework.permissions.IsAuthenticatedOrReadOnly', # 未登录用户只能读，登录用户可以读写
    #     'rest_framework.permissions.IsAuthenticated', # 必须登录才能进行相应操作
    # ],
    'URL_FIELD_NAME': 'link', # HyperlinkedModelSerializer的url字段名，默认为url，可以自定义
}
